# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  mapit:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: situx/geordfconverter/.github/workflows/geordfconvert.yml@main
    with: 
        input: source/trinkwasser_brunnen_berlin.geojson
        output: docs
        ghpages: true
        addfiles: source/trinkwasser_brunnen_berlin_md.ttl 
        dcaturi: https://gdk.gdi-de.org/inspire/srv/eng/xml_iso19139?uuid=8aaca41b-d665-447a-93ec-b76e431852fc
        mapping: mappings/trinkwasserbrunnen.json
        sepchar: ";"

  mapit2:
    uses: situx/geordfconverter/.github/workflows/geordfconvert.yml@main
    needs: mapit
    with: 
        input: source/baumkataster_hamburg.geojson
        output: docs
        ghpages: true
        addfiles: source/baumkataster_hamburg_md.ttl 
        dcaturi: http://suche.transparenz.hamburg.de/dataset/dc163b2f-3fe3-4df3-96e9-b1c501b88ed7
        mapping: mappings/baumkataster.json
        sepchar: ";"

  vocbuild:
    runs-on: ubuntu-latest
    needs: 
      - mapit
      - mapit2
    steps:
    - uses: actions/checkout@v4
    - name: "Build Vocabulary documentation"
      run: | 
        sudo apt-get update
        sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
        sudo pip3 install wheel pylode==2.13.2
        mkdir docs
        mkdir docs/ont
        wget https://gdi-de.github.io/apworkshop2026_ldtutorial/source_baumkataster_hamburg_mappings_baumkataster_ont.ttl
        wget https://gdi-de.github.io/apworkshop2026_ldtutorial/source_trinkwasser_brunnen_berlin_mappings_trinkwasserbrunnen_ont.ttl
        sed '/^@/d' source_trinkwasser_brunnen_berlin_mappings_trinkwasserbrunnen_ont.ttl > brunnenmod.ttl
        sed '/^[^@]/d' source_trinkwasser_brunnen_berlin_mappings_trinkwasserbrunnen_ont.ttl > brunnenmodhead.ttl
        cat brunnenmodhead.ttl source_baumkataster_berlin_mappings_baumkataster_ont.ttl brunnenmod.ttl > forpylode.ttl
        cat forpylode.ttl
        pylode -o docs/ont/index.html -i forpylode.ttl
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
         clean: false     
          

  
  # This workflow contains a single job called "build"  
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    needs: 
      - mapit
      - mapit2
      - vocbuild
    with: 
        version: v018
        rdffilepath: source_baumkataster_berlin_mappings_baumkataster.ttl source_trinkwasser_brunnen_berlin_mappings_trinkwasserbrunnen.ttl
        rdffilebranch: gh-pages
        docpath: docs
        prefixns: https://gdi-de.github.io/apworkshop2026/
        prefixnsshort: gdide
        indexpages: true
        createcollections: true
        createnonNSPages: true
        createVOWL: true
        metadatatable: true
        preferredlang: en
        license: CC BY 4.0
        ghpages: true
